"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character] 
# success_symbol = "[ğŸ‘¾](bold green)"
# error_symbol = "[ğŸ‘¾](bold red)"
success_symbol = "[Â»](bold green)"
error_symbol = "[Â»](bold red)"

[package]
disabled = false

