live_config_reload = true

[colors.primary]
background = '#15141b'
foreground = '#edecee'

# Normal colors
[colors.normal]
black = '#110f18'
red = '#ff6767'
green = '#61ffca'
yellow = '#ffca85'
blue = '#a277ff'
magenta = '#a277ff'
cyan = '#61ffca'
white = '#edecee'

# Bright colors
[colors.bright]
black = '#4d4d4d'
red = '#ff6767'
green = '#61ffca'
yellow = '#ffca85'
blue = '#a277ff'
magenta = '#a277ff'
cyan = '#61ffca'
white = '#edecee'

[colors.selection]
text = 'CellForeground'
background = '#29263c'

[colors.cursor]
cursor = '#a277ff'

# [colors.bright]
# black = "#5c5c5c"
# red = "#ff5370"
# green = "#c3e88d"
# yellow = "#ffcb6b"
# blue = "#82aaff"
# magenta = "#ff79c6"
# cyan = "#89ddff"
# white = "#ffffff"

# [colors.cursor]
# cursor = '#afafae'

# [colors.normal]
# black = "#000000"
# red = "#e06c75"
# green = "#98c379"
# yellow = "#d19a66"
# blue = "#61afef"
# magenta = "#c678dd"
# cyan = "#56b6c2"
# white = "#ababab"

# [colors.primary]
# background = "#1e1e1e"
# foreground = "#f8f8f8"

# [colors.selection]
# background = '#2e4e75'
# text = "CellForeground"

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "MonoLisa Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "MonoLisa Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mode = "~Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "HideOtherApplications"
key = "H"
mods = "Command|Alt"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B"
key = "Right"
mods = "Alt"

[[mouse.bindings]]
action = "ExpandSelection"
mouse = "Right"

[[mouse.bindings]]
action = "ExpandSelection"
mods = "Control"
mouse = "Right"

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = false
opacity = 1
startup_mode = "Maximized"
title = "Terminal"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 5

[window.position]
x = 10
y = 10
